### ISSUE TITLE
Crash on server start?

### ISSUE THREAD

**Issue by distortedsignal** [erlang-ls/erlang_ls#565]
Hey all,

I want to try using this project with Sublime Text 3, and I downloaded it and tried to get it working. My binary is located on my path, like so:

```sh
> which erlang_ls
/Users/tom/.local/bin/erlang_ls
```

The version is reported as follows:

```sh
> erlang_ls --version
Version: 0.2.0+build.866.refcc21af1
```

And I am trying to use the "host-general" `erlang_ls.config` file. Mine is here:

```yaml
otp_path: "/Users/tom/.kerl/21.3"
deps_dirs:
  - "/Users/tom/Documents/src/project/specific/deps/dir/deps"
include_dirs:
  - "include"
  - "_build/default/lib"
  - "/Users/tom/Documents/src/project/specific/*/include"
code_reload:
  node: node@example

```

I know there are a lot of project-specific things in there, but I don't want to clog up the git repo with my own tools.

When I open sublime text (with an erlang file loaded), I get the following logs in the server logs and the crash logs:

server.log:
```
2020-03-13 13:39:28.454 [info] <0.167.0>@els_sup:restrict_stdio_access:76 Use group leader as io_device
2020-03-13 13:39:28.454 [info] <0.167.0>@els_sup:restrict_stdio_access:83 Replace group leader to avoid unwanted output to stdout
2020-03-13 13:39:28.458 [info] <0.169.0>@els_server:init:99 Starting els_server...
2020-03-13 13:39:28.460 [info] <0.170.0>@els_stdio:init:22 Starting stdio server...
2020-03-13 13:39:28.494 [info] <0.8.0>@erlang_ls:main:23 Started erlang_ls server
2020-03-13 13:39:28.502 [info] <0.169.0>@els_config:consult_config:183 Reading config file. path="/Users/tom/Documents/src/project/erlang_ls.config"
2020-03-13 13:39:28.513 [warning] <0.169.0>@els_config:consult_config:190 Could not read config file: path="/Users/tom/Documents/src/project/erlang_ls.config" class=throw error={yamerl_exception,[{yamerl_parsing_error,error,"Failed to open file \"/Users/tom/Documents/src/project/erlang_ls.config\": no such file or directory",undefined,undefined,file_open_failure,undefined,[{error,enoent}]}]}
2020-03-13 13:39:28.513 [info] <0.169.0>@els_config:consult_config:183 Reading config file. path="/Users/tom/Library/Application Support/erlang_ls/erlang_ls.config"
2020-03-13 13:39:28.591 [info] <0.169.0>@els_config:do_initialize:92 Excluded OTP Applications: ["megaco","diameter","snmp","wx"]
2020-03-13 13:39:28.703 [info] <0.169.0>@els_db:install:29 Switching to distribute mode
2020-03-13 13:39:28.747 [info] <0.169.0>@els_db:install:32 Distributed mode enabled [node=erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366]
2020-03-13 13:39:28.747 [info] <0.169.0>@els_db:install:34 Configuring DB [dir=/Users/tom/Library/Caches/erlang_ls/erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366]
2020-03-13 13:39:28.747 [info] <0.169.0>@els_db:maybe_delete_db_schema:164 DB Schema up to date [dir=/Users/tom/Library/Caches/erlang_ls/erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366] [vsn=5]
2020-03-13 13:39:28.822 [info] <0.169.0>@els_db:ensure_db:53 DB Schema already exists, skipping
2020-03-13 13:39:28.822 [info] <0.169.0>@els_db:ensure_db:59 Preparing tables
2020-03-13 13:39:31.977 [info] <0.169.0>@els_db:ensure_db:63 DB Initialized
2020-03-13 13:39:32.411 [info] <0.169.0>@els_methods:exit:207 Language server stopping...
2020-03-13 13:39:32.412 [error] <0.167.0> Supervisor els_sup had child els_indexer started with els_indexer:start_link() at <0.172.0> exit with reason shutdown in context child_terminated
2020-03-13 13:39:32.874 [info] <0.43.0> Application mnesia exited with reason: stopped
```

crash.log:
```
2020-03-13 13:38:36 =SUPERVISOR REPORT====
     Supervisor: {local,els_sup}
     Context:    child_terminated
     Reason:     shutdown
     Offender:   [{pid,<0.172.0>},{id,els_indexer},{mfargs,{els_indexer,start_link,[]}},{restart_type,permanent},{shutdown,brutal_kill},{child_type,worker}]

```

Looks like I'm getting `brutal_kill`'d by something?

One more piece of info that is maybe helpful is the LSP settings inside of ST3 - here:

```json
{
	"clients":
	{
		"erlang-ls":
		{
			"command":
			[
				"/Users/tom/.local/bin/erlang_ls",
				"--transport",
				"stdio"
			],
			"enabled": true,
			"languageId": "erlang",
			"scopes":
			[
				"source.erlang"
			],
			"syntaxes":
			[
				"Packages/Erlang/Erlang.sublime-syntax"
			]
		}
	}
}
```

Any help is welcome.

**Comment by gilbertwong96** [comment]
Is your projects structure a common rebar3 project? 

Here is my global erlang_ls.config:

```
otp_path: "/Users/gilbertwong/Documents/opensource/otp/"
deps_dirs:
  - "_build/default/lib/*"
  - "_build/test/lib/*"
include_dirs:
  - "include"
  - "_build/default/lib"
  - "_build/test/lib"
```

**Comment by distortedsignal** [comment]
rebar3? Not quite... the company that I work for is on 1st gen rebar - is that a problem?

**Comment by robertoaloi** [comment]
Hi @distortedsignal , thanks for getting in touch.

Erlang LS does not assume a `rebar3` project structure and this does not look like a configuration error, so you are good to go.

There's a know bug with the Sublime Text 3, where the `RootUri` is not correctly handled during initialization in some cases. See: https://github.com/erlang-ls/erlang_ls/issues/400
To verify you're hitting that bug, could you send us the body of the initialization request which is sent by the Sublime client? This section explains how to enable logging for Sublime Text 3:

https://erlang-ls.github.io/editors/sublime3/

As a workaround, you should be able to first open the project **directory** and only after the actual the source file you want to edit.

Other things you could try (one at the time, so we can pinpoint the actual issue):

1. Remove the `code_reload` option
2. Switch to a TCP transport. In this case just replace the `transport` in your options to `tcp` and add a `"tcp_port": 1000` under `clients`

Let us know if this helps!

**Comment by distortedsignal** [comment]
Ok, so my settings file now looks like this:

```json
{
	"clients":
	{
		"erlang-ls":
		{
			"command":
			[
				"/Users/tom/.local/bin/erlang_ls",
				"--transport",
				"stdio"
			],
			"enabled": true,
			"languageId": "erlang",
			"scopes":
			[
				"source.erlang"
			],
			"syntaxes":
			[
				"Packages/Erlang/Erlang.sublime-syntax"
			]
		}
	},
    // Show verbose debug messages in the sublime console.
    "log_debug": true,

    // Show messages from language servers in the Language Servers output
    // panel.
    "log_server": true,

    // Show language server stderr output in the Language Servers output
    // panel.
    "log_stderr": true,

    // Show full JSON-RPC requests/responses/notifications in the Language
    // Servers output panel.
    "log_payloads": true
}
```

And the log output looks like this:

```
SublimeLinter: sublime_linter.py:324  Delay linting 'bd_mgmt_identity_saml.erl' for 0.0s
LSP: window 2 requests erlang-ls for /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/src/bd_mgmt_identity_saml.erl
LSP: starting ['/Users/tom/.local/bin/erlang_ls', '--transport', 'stdio']
LSP: window 2 added session erlang-ls
SublimeLinter: sublime_linter.py:340  No installed linter matches the view.
erlang-ls for /Users/tom/Documents/src/BlueData/everest did not initialize properly. Disabling until this window is restarted
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 334, in get_session
    return self._find_session(config_name, file_path)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 344, in _find_session
    if session.handles_path(file_path):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 198, in handles_path
    with self.acquire_timeout():
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 191, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: erlang-ls did not respond to the initialize request within 3 seconds

LSP: single folder session: [WorkspaceFolder('everest', '/Users/tom/Documents/src/BlueData/everest')]
LSP: session erlang-ls ended
Error handling server payload
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 218, in response_handler
    request_id = int(response["id"])
TypeError: int() argument must be a string or a number, not 'NoneType'

Error handling server payload
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 218, in response_handler
    request_id = int(response["id"])
TypeError: int() argument must be a string or a number, not 'NoneType'

LSP:LSP: process 39045 stdout ended (still alive)
 LSP: process 39045 exited with code 0
LSP stream logger stopped.
```

It looks like this might be the null issue?

**Comment by distortedsignal** [comment]
@robertoaloi I'm unclear what `code_reload` option your discussing in your comment - could you go into more detail on that?

**Comment by distortedsignal** [comment]
Trying with the port-based setup, I'm not sure that it's working quite as intended. I got this message from ST3:

```
SublimeLinter: sublime_linter.py:324  Delay linting 'bd_mgmt_identity_saml.erl' for 0.0s
LSP: window 2 requests erlang-ls for /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/src/bd_mgmt_identity_saml.erl
LSP: starting ['/Users/tom/.local/bin/erlang_ls', '--transport', 'tcp', '--port', '12000']
LSP: window 2 added session erlang-ls
SublimeLinter: sublime_linter.py:340  No installed linter matches the view.
erlang-ls for /Users/tom/Documents/src/BlueData/everest did not initialize properly. Disabling until this window is restarted
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 334, in get_session
    return self._find_session(config_name, file_path)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 344, in _find_session
    if session.handles_path(file_path):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 198, in handles_path
    with self.acquire_timeout():
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 191, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: erlang-ls did not respond to the initialize request within 3 seconds
```

And then I tried to start the server on my own, like this:

```zsh
> erlang_ls --transport tcp --port 12000
```

I thought that it was taking quite a while to start up, so I did the following:

```zsh
> ls -lahtR ~/Library/Caches/erlang_ls
total 8
drwx------+ 138 tom  staff   4.3K Mar 16 10:07 ..
drwxr-xr-x   10 tom  staff   320B Mar 16 09:50 erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366
-rw-r--r--    1 tom  staff     1B Mar 16 09:50 DB_SCHEMA_VSN
drwxr-xr-x    6 tom  staff   192B Mar 13 13:11 .
drwxr-xr-x    9 tom  staff   288B Mar 13 12:39 erlang_ls_3de8a13d69b13345d73d6ebb659417c47fa6be01
drwxr-xr-x    9 tom  staff   288B Mar 13 11:50 erlang_ls_aa7c2bbe233993dc5e30a98d181fa14613ab8597

/Users/tom/Library/Caches/erlang_ls/erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366:
total 392904
-rw-r--r--   1 tom  staff   144B Mar 16 09:50 els_dt_document.TMP
-rw-r--r--   1 tom  staff   146B Mar 16 09:50 LATEST.LOG
drwxr-xr-x  10 tom  staff   320B Mar 16 09:50 .
-rw-r--r--   1 tom  staff   210B Mar 16 09:50 DECISION_TAB.LOG
-rw-r--r--   1 tom  staff    23M Mar 13 13:15 els_dt_signatures.DCD
-rw-r--r--   1 tom  staff   1.5M Mar 13 13:15 els_dt_references.DCD
-rw-r--r--   1 tom  staff   122K Mar 13 13:15 els_dt_document_index.DCD
-rw-r--r--   1 tom  staff   166M Mar 13 13:15 els_dt_document.DCD
-rw-r--r--   1 tom  staff    11K Mar 13 13:11 schema.DAT
drwxr-xr-x   6 tom  staff   192B Mar 13 13:11 ..

/Users/tom/Library/Caches/erlang_ls/erlang_ls_3de8a13d69b13345d73d6ebb659417c47fa6be01:
total 72
drwxr-xr-x  6 tom  staff   192B Mar 13 13:11 ..
-rw-r--r--  1 tom  staff   146B Mar 13 12:39 LATEST.LOG
drwxr-xr-x  9 tom  staff   288B Mar 13 12:39 .
-rw-r--r--  1 tom  staff   144B Mar 13 12:39 els_dt_signatures.DCD
-rw-r--r--  1 tom  staff   144B Mar 13 12:39 els_dt_references.DCD
-rw-r--r--  1 tom  staff   144B Mar 13 12:39 els_dt_document_index.DCD
-rw-r--r--  1 tom  staff   144B Mar 13 12:39 els_dt_document.DCD
-rw-r--r--  1 tom  staff   207B Mar 13 12:39 DECISION_TAB.LOG
-rw-r--r--  1 tom  staff    11K Mar 13 12:39 schema.DAT

/Users/tom/Library/Caches/erlang_ls/erlang_ls_aa7c2bbe233993dc5e30a98d181fa14613ab8597:
total 406912
drwxr-xr-x  6 tom  staff   192B Mar 13 13:11 ..
-rw-r--r--  1 tom  staff   146B Mar 13 12:39 LATEST.LOG
drwxr-xr-x  9 tom  staff   288B Mar 13 11:50 .
-rw-r--r--  1 tom  staff    25M Mar 13 11:50 els_dt_signatures.DCD
-rw-r--r--  1 tom  staff   118K Mar 13 11:50 els_dt_references.DCD
-rw-r--r--  1 tom  staff   128K Mar 13 11:50 els_dt_document_index.DCD
-rw-r--r--  1 tom  staff   169M Mar 13 11:50 els_dt_document.DCD
-rw-r--r--  1 tom  staff   210B Mar 13 11:50 DECISION_TAB.LOG
-rw-r--r--  1 tom  staff    11K Mar 13 09:23 schema.DAT
```

Are these values expected? 23 MB of els_dt_signatures? 166 MB of documentation? Could it be that this is just taking a _long_ time to read some files?

**Comment by distortedsignal** [comment]
I also tried this with a TCP config:

Plugin Config:
```json
{
	"clients":
	{
		"erlang-ls":
		{
            "tcp_port": 12000,
			"command":
			[
				"/Users/tom/.local/bin/erlang_ls",
				"--transport",
				"tcp",
                "--port",
                "12000",
                "-l",
                "debug"
			],
			"enabled": true,
			"languageId": "erlang",
			"scopes":
			[
				"source.erlang"
			],
			"syntaxes":
			[
				"Packages/Erlang/Erlang.sublime-syntax"
			]
		}
	},
    "log_debug": true,
    "log_server": true,
    "log_stderr": true,
    "log_payloads": true
}
```

Sublime Logs:
```
SublimeLinter: sublime_linter.py:324  Delay linting 'bd_mgmt_identity_saml.erl' for 0.0s
LSP: window 2 requests erlang-ls for /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/src/bd_mgmt_identity_saml.erl
LSP: starting ['/Users/tom/.local/bin/erlang_ls', '--transport', 'tcp', '--port', '12000', '-l', 'debug']
LSP: connecting to localhost:12000
LSP: window 2 added session erlang-ls
SublimeLinter: linter.py:1103         erlc: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #1 linter.py:1120      erlc: linting 'bd_mgmt_identity_saml.erl'
SublimeLinter: #1 util.py:163         PATH:
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /usr/local/MacGPG2/bin
    /Applications/Wireshark.app/Contents/MacOS
SublimeLinter: #1 linter.py:1636      Running ...

  /Users/tom/Documents/src/BlueData/everest  (working dir)
  $ /usr/local/bin/erlc -W -I /Users/tom/Documents/src/BlueData/everest/io/base/apps/bd_logger/include -I /Users/tom/Documents/src/BlueData/everest/io/base/apps/bds_memq/include -I /Users/tom/Documents/src/BlueData/everest/io/base/apps/data_server/include -I /Users/tom/Documents/src/BlueData/everest/io/base/private/include -I /Users/tom/Documents/src/BlueData/everest/io/base/tools/bds_io_bqs/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_ha/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_hypervisor_agent/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_hypervisor_controller/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_hypervisor_controller/legacy_include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/legacy_include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_os_client/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_throttle/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_util/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/deps/mochiweb/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/shared/bd_shared/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/vm/vagent/bd_vagent/include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/deps -I /Users/tom/Documents/src/BlueData/everest/mgmt/shared/bd_shared/legacy_include -I /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_kube_authn/include -o . /Users/tom/Documents/src/BlueData/everest/mgmt/controller/server/bd_mgmt/src/bd_mgmt_identity_saml.erl

SublimeLinter: #1 linter.py:1196      erlc: no output
SublimeLinter: sublime_linter.py:575  Linting 'bd_mgmt_identity_saml.erl' took 0.74s
erlang-ls for /Users/tom/Documents/src/BlueData/everest did not initialize properly. Disabling until this window is restarted
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 334, in get_session
    return self._find_session(config_name, file_path)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 344, in _find_session
    if session.handles_path(file_path):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 198, in handles_path
    with self.acquire_timeout():
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 191, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: erlang-ls did not respond to the initialize request within 3 seconds

LSP: single folder session: [WorkspaceFolder('everest', '/Users/tom/Documents/src/BlueData/everest')]
LSP: session erlang-ls ended
Error handling server payload
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 218, in response_handler
    request_id = int(response["id"])
TypeError: int() argument must be a string or a number, not 'NoneType'

Error handling server payload
Traceback (most recent call last):
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "/Users/tom/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 218, in response_handler
    request_id = int(response["id"])
TypeError: int() argument must be a string or a number, not 'NoneType'

LSP: no data received, closing
```

Server logs:

```
2020-03-16 10:46:11.136 [debug] <0.129.0>@lager_handler_watcher:126 Lager installed handler error_logger_lager_h into error_logger
2020-03-16 10:46:11.573 [info] <0.168.0>@els_server:init:99 Starting els_server...
2020-03-16 10:46:11.575 [info] <0.167.0>@els_tcp:start_listener:46 Starting ranch listener..

2020-03-16 10:48:56.422 [info] <0.168.0>@els_config:consult_config:183 Reading config file. path="/Users/tom/Documents/src/BlueData/everest/erlang_ls.config"
2020-03-16 10:48:56.445 [warning] <0.168.0>@els_config:consult_config:190 Could not read config file: path="/Users/tom/Documents/src/BlueData/everest/erlang_ls.config" class=throw error={yamerl_exception,[{yamerl_parsing_error,error,"Failed to open file \"/Users/tom/Documents/src/BlueData/everest/erlang_ls.config\": no such file or directory",undefined,undefined,file_open_failure,undefined,[{error,enoent}]}]}
2020-03-16 10:48:56.445 [info] <0.168.0>@els_config:consult_config:183 Reading config file. path="/Users/tom/Library/Application Support/erlang_ls/erlang_ls.config"
2020-03-16 10:48:56.676 [info] <0.168.0>@els_config:do_initialize:92 Excluded OTP Applications: ["megaco","diameter","snmp","wx"]
2020-03-16 10:48:56.937 [info] <0.168.0>@els_db:install:29 Switching to distribute mode
2020-03-16 10:48:57.017 [info] <0.168.0>@els_db:install:32 Distributed mode enabled [node=erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366]
2020-03-16 10:48:57.017 [info] <0.168.0>@els_db:install:34 Configuring DB [dir=/Users/tom/Library/Caches/erlang_ls/erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366]
2020-03-16 10:48:57.018 [info] <0.168.0>@els_db:maybe_delete_db_schema:164 DB Schema up to date [dir=/Users/tom/Library/Caches/erlang_ls/erlang_ls_89a7110e54bf1f5a1cbc4332f6bdd0810a0a8366] [vsn=5]
2020-03-16 10:48:57.204 [info] <0.168.0>@els_db:ensure_db:53 DB Schema already exists, skipping
2020-03-16 10:48:57.204 [info] <0.168.0>@els_db:ensure_db:59 Preparing tables
2020-03-16 10:48:57.150 [debug] <0.129.0>@lager_handler_watcher:126 Lager installed handler error_logger_lager_h into error_logger
2020-03-16 10:48:57.565 [debug] <0.121.0>@lager_handler_watcher:126 Lager installed handler lager_backend_throttle into lager_event
2020-03-16 10:48:57.764 [info] <0.168.0>@els_server:init:99 Starting els_server...
2020-03-16 10:48:57.766 [info] <0.167.0>@els_tcp:start_listener:46 Starting ranch listener..
2020-03-16 10:49:00.910 [info] <0.168.0>@els_db:ensure_db:63 DB Initialized
2020-03-16 10:49:01.503 [info] <0.168.0>@els_methods:exit:207 Language server stopping...
2020-03-16 10:49:01.504 [error] <0.167.0> Supervisor els_sup had child els_indexer started with els_indexer:start_link() at <0.183.0> exit with reason shutdown in context child_terminated
2020-03-16 10:49:02.144 [info] <0.43.0> Application mnesia exited with reason: stopped
```

More data, might be interesting.

The issue with the prior TCP setup might have been a PICNIC error - not putting the port in the right JSON context.

**Comment by jfacorro** [comment]
Hi @distortedsignal, the issue you are having above is because `erlang_ls` is taking more than 3 seconds to respond to the `initialize` request. I was testing `erlang_ls` with Sublime Text today and found the same problem you are describing in the last message above. To avoid this problem it's necessary to increase the timeout for the `initialize` request. Please check the `"initialize_timeout"` value in the following configuration:

``` json
{
  "clients":
    {
      "erlang-ls":
        {
          "command"   : [ "/usr/local/bin/erlang_ls", "--transport", "stdio", "--log-level", "debug" ],
          "enabled"   : true,
          "languageId": "erlang",
          "scopes"    : [ "source.erlang" ],
          "syntaxes"  : ["Packages/Erlang/Erlang.sublime-syntax"]
        }
    },
  "log_debug": true,
  "log_payloads": true,
  "initialize_timeout": 30
}
```

I think if you do this you will get it working.

**Comment by distortedsignal** [comment]
Yes! That works! Thank you so much! Now I can get to filing different issues I'm having 😀

**Comment by robertoaloi** [comment]
Glad that it works! Thanks @jfacorro !

**Comment by robertoaloi** [comment]
Adding to the Sublime docs: https://github.com/erlang-ls/erlang-ls.github.io/pull/4
